- name: Connecting EC2 through SSH
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_PRIVATE_KEY }}
    script_stop: true
    script: |
      rm -rf /home/ubuntu/app/deploy
      mkdir /home/ubuntu/app/deploy
      mv /home/ubuntu/app/app.jar /home/ubuntu/app/deploy/app.jar
      cd /home/ubuntu/app/deploy
      sudo fuser -k -n tcp 8080 || true
      nohup java -jar app.jar > ./output.log 2>&1 &
      rm -rf /home/ubuntu/app