- name: File made by Github Actions ubuntu
  run: touch actions-file.log

- name: From Github Actions to AWS EC2 through SCP
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_PRIVATE_KEY }}
    source: actinos-file.log
    target: /home/ubuntu